#!/usr/bin/env python3

import sys
import os
import glob

def main():
    if len(sys.argv) < 2:
        print("Usage: python script.py <relative_directory>")
        sys.exit(1)
    
    # ----------------------------
    # Parameterize styles here
    # ----------------------------
    icon_color = "ff0000ff"  # AABBGGRR format (alpha, blue, green, red)
    icon_scale = "3"       # Marker size
    # icon_href  = "http://maps.google.com/mapfiles/kml/shapes/placemark_circle.png"
    icon_href = "http://maps.google.com/mapfiles/kml/paddle/wht-blank.png"
    # Other valid shapes might include:
    # http://maps.google.com/mapfiles/kml/shapes/placemark_square.png
    # http://maps.google.com/mapfiles/kml/shapes/placemark_circle.png

    # Directory containing text files
    directory = sys.argv[1]
    
    # Gather all coordinates
    all_coordinates = []
    for file_path in glob.glob(os.path.join(directory, "*.txt")):
        with open(file_path, "r", encoding="utf-8") as f:
            for line in f:
                line = line.strip()
                if not line:
                    continue
                # Each line in the file: lat,lon
                lat, lon = line.split(",")
                lat, lon = lat.strip(), lon.strip()
                all_coordinates.append((lat, lon))

    # Build the KML content
    kml_content = []
    kml_content.append('<?xml version="1.0" encoding="UTF-8"?>')
    kml_content.append('<kml xmlns="http://www.opengis.net/kml/2.2">')
    kml_content.append('  <Document>')
    kml_content.append('    <name>Coordinates KML</name>')
    kml_content.append('    <Style id="markerStyle">')
    kml_content.append('      <IconStyle>')
    kml_content.append(f'        <color>{icon_color}</color>')
    kml_content.append(f'        <scale>{icon_scale}</scale>')
    kml_content.append('        <Icon>')
    kml_content.append(f'          <href>{icon_href}</href>')
    kml_content.append('        </Icon>')
    kml_content.append('      </IconStyle>')
    kml_content.append('    </Style>')

    # Add placemarks
    for i, (lat, lon) in enumerate(all_coordinates, start=1):
        kml_content.append('    <Placemark>')
        kml_content.append(f'      <name>Point #{i}</name>')
        kml_content.append('      <description>Generated by Python Script</description>')
        kml_content.append('      <styleUrl>#markerStyle</styleUrl>')
        kml_content.append('      <Point>')
        kml_content.append(f'        <coordinates>{lon},{lat},0</coordinates>')
        kml_content.append('      </Point>')
        kml_content.append('    </Placemark>')

    # Close out the KML
    kml_content.append('  </Document>')
    kml_content.append('</kml>')

    # Write to output.kml
    with open("output.kml", "w", encoding="utf-8") as out_kml:
        out_kml.write("\n".join(kml_content))

if __name__ == "__main__":
    main()
